In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"/dataset_Facebook.csv",sep=";")

In [ ]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [ ]:
df1 = df[['Page total likes','Category','Post Month','Post Weekday']].loc[0:15]

In [ ]:
df1

    Page total likes  Category  Post Month  Post Weekday
0             139441         2          12             4
1             139441         2          12             3
2             139441         3          12             3
3             139441         2          12             2
4             139441         2          12             2
5             139441         2          12             1
6             139441         3          12             1
7             139441         3          12             7
8             139441         2          12             7
9             139441         3          12             6
10            139441         2          12             5
11            139441         2          12             5
12            139441         2          12             5
13            139441         2          12             5
14            138414         2          12             4
15            138414         2          12             3

In [ ]:
df2 = df[['Page total likes','Category','Post Month','Post Weekday']].loc[16:30]
df2

    Page total likes  Category  Post Month  Post Weekday
16            138414         3          12             3
17            138414         1          12             2
18            138414         3          12             2
19            138414         3          12             1
20            138414         2          12             1
21            138414         1          12             7
22            138414         1          12             7
23            138414         3          12             7
24            138414         2          12             6
25            138458         2          12             6
26            138458         2          12             5
27            138458         3          12             5
28            138895         2          12             5
29            138895         1          12             4
30            138895         2          12             4

In [ ]:
df3 = df[['Page total likes','Category','Post Month','Post Weekday']].loc[31:40]

In [ ]:
df3

    Page total likes  Category  Post Month  Post Weekday
31            138895         2          12             3
32            138895         3          12             3
33            138895         3          12             2
34            138895         1          12             2
35            138895         2          12             1
36            138895         3          12             1
37            138895         1          12             7
38            138895         2          12             7
39            138895         1          12             7
40            138895         2          12             6

In [ ]:
merging = pd.concat([df1,df2,df3])
merging

    Page total likes  Category  Post Month  Post Weekday
0             139441         2          12             4
1             139441         2          12             3
2             139441         3          12             3
3             139441         2          12             2
4             139441         2          12             2
5             139441         2          12             1
6             139441         3          12             1
7             139441         3          12             7
8             139441         2          12             7
9             139441         3          12             6
10            139441         2          12             5
11            139441         2          12             5
12            139441         2          12             5
13            139441         2          12             5
14            138414         2          12             4
15            138414         2          12             3
16            138414         3          12             3
17            138414         1          12             2
18            138414         3          12             2
19            138414         3          12             1
20            138414         2          12             1
21            138414         1          12             7
22            138414         1          12             7
23            138414         3          12             7
24            138414         2          12             6
25            138458         2          12             6
26            138458         2          12             5
27            138458         3          12             5
28            138895         2          12             5
29            138895         1          12             4
30            138895         2          12             4
31            138895         2          12             3
32            138895         3          12             3
33            138895         3          12             2
34            138895         1          12             2
35            138895         2          12             1
36            138895         3          12             1
37            138895         1          12             7
38            138895         2          12             7
39            138895         1          12             7
40            138895         2          12             6

In [ ]:
sort_values = df.sort_values('Page total likes', ascending=False)
sort_values

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [ ]:
shaping = df.shape
shaping

(500, 19)

In [ ]:
pivot_table = pd.pivot_table(df,index=['Type','Category'],values='like')
print(pivot_table)

                       like
Type   Category
Link   1          75.650000
       2          32.000000
       3          68.000000
Photo  1         126.000000
       2         235.857143
       3         219.753333
Status 1         136.333333
       2         182.552632
       3         151.500000
Video  1         231.428571

In [ ]:
reshaping_arr = np.array([1,2,3,4,5,6])
reshaping_arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])